#Gradle
org.gradle.jvmargs=-Xmx4608m -Dkotlin.daemon.jvm.options\="-Xmx4608m"

#Kotlin
kotlin.code.style=official

#Android
android.useAndroidX=true

#MPP
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.cacheKind=none

#Publishing
publishGroupId=com.swensonhe
publishEmail=developer@swensonhe.com
publishRepository=https://github.com/swensonhe/strapi-kmm
publishDeveloper=SwensonHe Developer
