#Gradle
org.gradle.jvmargs=-Xmx4608m -Dkotlin.daemon.jvm.options\="-Xmx4608m"

#Kotlin
kotlin.code.style=official

#Android
android.useAndroidX=true

#MPP
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.cacheKind=none

#Publishing
publishGroupId=com.metacto
publishEmail=developer@MetaCTO.com
publishRepository=https://github.com/Meta-CTO/strapi-kmm
publishDeveloper=MetaCTO Developer
